module.exports = request => ({

	Brand: require('./brand.js')(request),
	Cart: require('./cart.js')(request),
	Catalog: require('./catalog.js')(request),
	Collection: require('./collection.js')(request),
	Country: require('./country.js')(request),
	Coupon: require('./coupon.js')(request),
	Currency: require('./currency.js')(request),
	Customer: require('./customer.js')(request),
	Group: require('./group.js')(request),
	Image: require('./image.js')(request),
	Order: require('./order.js')(request),
	OrderTag: require('./orderTag.js')(request),
	PaymentMethod: require('./paymentMethod.js')(request),
	Product: require('./product.js')(request),
	Review: require('./review.js')(request),
	ReviewComment: require('./reviewComment.js')(request),
	ShippingMethod: require('./shippingMethod.js')(request),
	Store: require('./store.js')(request),
	Subscription: require('./subscription.js')(request),
	SubscriptionPlan: require('./subscriptionPlan.js')(request),
	TaxCategory: require('./taxCategory.js')(request),
	Vendor: require('./vendor.js')(request),
	WishList: require('./wishList.js')(request),

});