module.exports = request => ({

	BlogCategory: require('./blogCategory.js')(request),
	BlogComment: require('./blogComment.js')(request),
	BlogPost: require('./blogPost.js')(request),
	Brand: require('./brand.js')(request),
	Collection: require('./collection.js')(request),
	Country: require('./country.js')(request),
	Coupon: require('./coupon.js')(request),
	Currency: require('./currency.js')(request),
	Customer: require('./customer.js')(request),
	Departure: require('./departure.js')(request),
	Discount: require('./discount.js')(request),
	Downloadable: require('./downloadable.js')(request),
	Group: require('./group.js')(request),
	Image: require('./image.js')(request),
	ImageBundle: require('./imageBundle.js')(request),
	Metafield: require('./metafield.js')(request),
	OrderTag: require('./orderTag.js')(request),
	Product: require('./product.js')(request),
	ProductAnswer: require('./productAnswer.js')(request),
	ProductQuestion: require('./productQuestion.js')(request),
	Review: require('./review.js')(request),
	ReviewComment: require('./reviewComment.js')(request),
	Shipping: require('./shipping.js')(request),
	ShippingMethod: require('./shippingMethod.js')(request),
	SupportCategory: require('./supportCategory.js')(request),
	SupportComment: require('./supportComment.js')(request),
	SupportPost: require('./supportPost.js')(request),
	Tax: require('./tax.js')(request),
	TaxCategory: require('./taxCategory.js')(request),
	WishList: require('./wishList.js')(request),

});